add cvector to lib9wada
BnademOverflow/libCplus pull request #5
Opened 2021-03-23 22:40 UTC by CollinBelmo

cvector is dynamic array implementation (basic data structure)

2021-03-23 22:42 UTC, KernelOverseer commented
I'll review the code tomorrow, thanks for your contribution

2021-03-23 22:43 UTC, yezz123 approved these changes

2021-03-24 17:05 UTC, KernelOverseer commented on includes/cvector.h
> +cvector *create(void);
I think function names should change to have a prefix, like `cvector_create` and `cvector_push_back` so there is no conflict with similar named functions in the future.

2021-03-24 17:07 UTC, KernelOverseer commented on sources/cvector/cvector.c
> +    vec->data = malloc(sizeof(void*) * INITIAL_SIZE);
A good practice is to check for malloc's return.
So when the allocation fails, the element just does not get created,
instead of having a bus error trying to access `NULL` address.

2021-03-24 17:08 UTC, KernelOverseer commented on sources/cvector/cvector.c
> +    if ((vec == NULL) || (vec->data == NULL))
I see that malloc's return here is checked, but don't you think the line before with memset can cause a problem ?

2021-03-24 17:09 UTC, KernelOverseer commented on sources/cvector/cvector.c
> +void delete(cvector *vec){
i suggest having a more versatile version of delete that takes a function pointer,
So if it's a list of some struct, you can pass a function that frees all the struct's fields correctly.

2021-03-24 17:12 UTC, KernelOverseer requested changes
Nice implementation and very helpful module,
Just some small changes following some best practices will make it better.

2021-03-24 17:24 UTC, KernelOverseer commented on sources/cvector/cvector.c
> +        exit(-1);
A program shouldn't always exit after malloc fails,
it's not up to this function to decide, it should only return NULL,
then the developer will take the decision depending on the usage.

2021-03-24 17:35 UTC, KernelOverseer commented
i'll do some other changes and then merge

2021-03-24 17:49 UTC, KernelOverseer approved these changes
All good now, tested wverything is working.thanks @CollinBelmo for the contribution :heart:

2021-03-24 17:49 UTC, merged